from enum import Enum


class UserRole(str, Enum):
    GOV_ADMIN = "GOV_ADMIN"
    BENEFICIARY_STUDENT = "BENEFICIARY_STUDENT"
    NGO_ORG = "NGO_ORG"
    MERCHANT = "MERCHANT"
    AUDITOR = "AUDITOR"


class GrantProgramStatus(str, Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    ARCHIVED = "ARCHIVED"


class GrantStatus(str, Enum):
    CREATED = "CREATED"
    APPROVED = "APPROVED"
    ISSUED = "ISSUED"
    RELEASED = "RELEASED"
    SPENDING_ACTIVE = "SPENDING_ACTIVE"
    SUSPENDED = "SUSPENDED"
    CLOSED = "CLOSED"
    REVOKED = "REVOKED"


class ApplicationStatus(str, Enum):
    SUBMITTED = "SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    VERIFIED = "VERIFIED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class VerificationStatus(str, Enum):
    PENDING = "PENDING"
    VERIFIED = "VERIFIED"
    FLAGGED = "FLAGGED"
    REJECTED = "REJECTED"


class TransactionDecision(str, Enum):
    APPROVED = "APPROVED"
    BLOCKED = "BLOCKED"


class MilestoneStatus(str, Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    SUBMITTED = "SUBMITTED"
    VERIFIED = "VERIFIED"
    APPROVED = "APPROVED"
    RELEASABLE = "RELEASABLE"
    RELEASED = "RELEASED"


class AuditEventType(str, Enum):
    GRANT_CREATED = "GRANT_CREATED"
    GRANT_APPROVED = "GRANT_APPROVED"
    GRANT_ISSUED = "GRANT_ISSUED"
    FUNDS_RELEASED = "FUNDS_RELEASED"
    SPENDING_REQUESTED = "SPENDING_REQUESTED"
    SPENDING_APPROVED = "SPENDING_APPROVED"
    SPENDING_BLOCKED = "SPENDING_BLOCKED"
    MILESTONE_CREATED = "MILESTONE_CREATED"
    EVIDENCE_SUBMITTED = "EVIDENCE_SUBMITTED"
    MILESTONE_APPROVED = "MILESTONE_APPROVED"
    TRANCHE_RELEASED = "TRANCHE_RELEASED"
    GRANT_SUSPENDED = "GRANT_SUSPENDED"
    GRANT_REVOKED = "GRANT_REVOKED"
    GRANT_CLOSED = "GRANT_CLOSED"
